# Generated by Django 5.2.8 on 2025-11-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=20)),
                ('pmid', models.CharField(blank=True, max_length=50, null=True)),
                ('titulo', models.TextField()),
                ('link', models.URLField()),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('autores', models.TextField(blank=True, null=True)),
                ('resumo', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('afiliacao', models.TextField(blank=True, null=True)),
                ('termo_de_busca', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
