# Generated by Django 5.2.8 on 2025-11-25 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(blank=True, max_length=500, verbose_name='termo')),
                ('origem', models.CharField(blank=True, max_length=200, verbose_name='origem(s)')),
                ('tipo', models.CharField(blank=True, max_length=50, verbose_name='tipo')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='data início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='data fim')),
                ('query_string', models.TextField(blank=True, verbose_name='query string')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Usuário que executou a busca (se autenticado)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Busca',
                'verbose_name_plural': 'Histórico de Buscas',
                'ordering': ['-created_at'],
            },
        ),
    ]
