# Generated by Django 5.2.8 on 2025-11-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca', '0002_searchhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtigoSalvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autores', models.CharField(blank=True, max_length=255, null=True)),
                ('ano', models.CharField(blank=True, max_length=10, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('resumo', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
