# Generated by Django 5.2.8 on 2025-11-28 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca', '0003_artigosalvo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da planilha')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planilhas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
                'unique_together': {('user', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='ItemPlanilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título')),
                ('autores', models.CharField(blank=True, max_length=500, verbose_name='Autores')),
                ('resumo', models.TextField(blank=True, verbose_name='Resumo')),
                ('data_publicacao', models.DateField(blank=True, null=True, verbose_name='Data de publicação')),
                ('origem', models.CharField(max_length=30, verbose_name='Origem')),
                ('link', models.URLField(verbose_name='Link')),
                ('adicionado_em', models.DateTimeField(auto_now_add=True)),
                ('planilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='busca.planilha')),
            ],
            options={
                'ordering': ['-adicionado_em'],
            },
        ),
    ]
